services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: ${NODE_ENV:-development}
    volumes:
      - ./backend:/usr/src/app
      - ./backend/db:/var/lib/postgresql/data
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=postgres://postgres:yourpassword@db:5432/yourdb
      - DOCKER=true
    command: npm run start:dev
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: ${NODE_ENV:-development}
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    command: npm run dev
    networks:
      - app-network

  db:
    image: postgres:15.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    volumes:
      - ./backend/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
